name: CI/CD MLOps Pipeline Wahib

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche `main`
  pull_request:
    branches:
      - main

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: projet_mlops

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v2

      - name: Configurer Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exécuter les tests
        run: python -m pytest -vv test.py

  cd_pipeline:
    needs: [ci_pipeline]
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v2

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Générer un tag basé sur la date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> "$GITHUB_ENV"

      - name: Construire et pousser l’image Docker
        run: |
          docker buildx create --use
          docker buildx build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$date --push
          docker buildx build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:latest --push
